### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#502] opened 2018-02-26 12:54 UTC
> Thank you for filing an issue!

### Version

Commit 89705fd7bd667aee5be5cbfbe1ed81228e2c806c

### Description

Webpack still shows some warnings while building:
![image](https://user-images.githubusercontent.com/5869273/36671589-68ed2358-1afc-11e8-8687-bfd036ac6208.png)

**Comment by okwme** [comment] 2018-05-16 10:48
unable to reproduce this bug after running:
```
git checkout 89705fd
rm -r node_modules
yarn
COSMOS_NODE=localhost yarn testnet
```
@mappum can you reproduce?

**Comment by faboweb** [comment] 2018-05-16 10:55
I confirm this error does not longer appear.

**Comment by faboweb** [comment] 2018-05-17 09:39
Happened again when building inside docker

**Comment by mappum** [comment] 2018-05-19 08:16
Confirmed this happens inside docker when building the app:
![](https://puu.sh/AoYe5/1c6e49094a.png)

But I'm wondering, why is this warning an issue? (Just because it's ugly to look at?) It's not actually causing any problems, and it's coming from the code in a dependency, not our own code (https://github.com/lukechilds/keyv/blob/master/src/index.js#L18).

Would it be acceptable to just hide the warning somehow?

**Comment by okwme** [comment] 2018-05-22 12:16
this is on the repo's issue tracker. they recommend closing your eyes when the warning appears:  
https://github.com/lukechilds/keyv/issues/45

**Comment by faboweb** [comment] 2018-05-22 13:39
So the proposal is to ignore the issue? (I am fine with it)

**Comment by okwme** [comment] 2018-05-22 14:13
closing

**Closed** 2018-06-25 13:22 UTC
Labels: bug
