### ISSUE TITLE
Spamming of 'setSubscription'

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1303] opened 2018-09-11 09:53 UTC
UI Version: 0.10.3

Description:

![image](https://user-images.githubusercontent.com/5869273/45352648-440bc780-b5b9-11e8-8b64-2ec573e3b26c.png)

The commit 'setSubscription' is called continuously.

**Comment by NodeGuy** [comment] 2018-11-05 18:40
I can't reproduce this.

**Comment by jbibla** [comment] 2018-11-06 03:20
i have definitely seen this (in the vue console)

**Comment by faboweb** [comment] 2018-11-06 12:57
Low priority as this doesn't effect the user

**Comment by NodeGuy** [comment] 2018-11-07 16:21
@faboweb You said we're not prioritizing bugs!

@jbibla Can you reproduce it?

**Comment by faboweb** [comment] 2018-11-07 21:06
I reproduced this issue.
We said we would always do bugs right away but for situations when we decide not do them as it is not important to do them. In this case the issue doesn't effect the user, so I thought we might as well not do the bug now.

**Comment by NodeGuy** [comment] 2018-11-08 18:43
> I reproduced this issue.

How did you reproduce the bug?  This information will be useful (necessary) for the developer assigned to fixing it.

> We said we would always do bugs right away but for situations when we decide not do them as it is not important to do them. In this case the issue doesn't effect the user, so I thought we might as well not do the bug now.

In that case it feels like I wasted effort classifying bugs not to be done now as low priority and then removing the labels at your direction.  Would you please go through the bugs and restore my labels?

**Comment by faboweb** [comment] 2018-11-11 14:19
> So are you saying that non-user facing bugs can be low priority and all user-facing bugs are implicitly high priority?

Sounds like a good sum up. Should we add this t our handbook?


> How did you reproduce the bug?

Like Jordan already mentioned: Open Voyager > Open Vue-Dev-Tools ( > maybe sign in) wait a couple of seconds.

**Comment by faboweb** [comment] 2018-11-20 11:09
This is called in `blockchain.js` on every block to show that the subscription is active. We just need to not send to commit if `state.subscription = true`.

**Closed** 2018-11-21 16:00 UTC
Labels: bug 🐞, low priority, reproduced
