### ISSUE TITLE
Workaround for locked keystore

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1376] opened 2018-09-28 16:54 UTC
The keystore in gaia gets locked by the process while in use. On reconnection we stop the gaia process and restart a new process. In some cases, the keystore is not released yet when we start the new gaia process. In that case the process crashes with following message:
```
gaiacli: panic: resource temporarily unavailable
````

Let's create a simple workaround for handling this case.

Proposed workaround:
- detect `resource temporarily unavailable` error
- wait a second
- retry connecting

**Comment by NodeGuy** [comment] 2018-09-28 19:40
Wouldn't it be better to fix this in Gaia?

**Comment by faboweb** [comment] 2018-10-01 08:30
There is already an open issue for that on the SDK: https://github.com/cosmos/cosmos-sdk/issues/1255
By reading the conversation there, I am not confident they will fix this soon.

**Comment by faboweb** [comment] 2018-10-02 11:07
Do you feel confident enough to fix this in the SDK?

**Comment by NodeGuy** [comment] 2018-10-02 20:00
That depends on whether I can reproduce the error.  I tried with this code but it doesn't fail:

```JavaScript
"use strict"

const child_process = require(`child_process`)
const path = require(`path`)

const child = child_process.spawn(
  path.join(__dirname, `builds/Gaia/darwin_amd64/gaiacli`),
  [`advanced`, `rest-server`],
  { stdio: `inherit` }
)

setTimeout(() => {
  child.kill()

  child_process.spawn(
    path.join(__dirname, `builds/Gaia/darwin_amd64/gaiacli`),
    [`advanced`, `rest-server`],
    { stdio: `inherit` }
  )
}, 1000)
````

**Comment by faboweb** [comment] 2018-10-03 17:05
I would start with running two processes at the same time. A timeout of 1 sec might already be enough to avoid the db lock. Which on second thought might be a feasible solution until this is fixed in the SDK.

**Comment by NodeGuy** [comment] 2018-10-03 20:21
Two processes running at the same time will create a lock conflict, even without stopping and restarting one of them.

**Comment by faboweb** [comment] 2018-10-04 07:14
That was the idea. What happens with a 50ms timeout?

**Comment by NodeGuy** [comment] 2018-10-04 19:11
OK then I'm not understanding something.  What are we trying to achieve here?  Successfully stopping one process and starting a new one, right?  There's no way that running two processes simultaneously can succeed, because LevelDB is locking the database, so trying that doesn't prove anything.

The code I wrote above uses no delay between killing and restarting the process so I don't see how adding a delay 50 ms would help either.

**Comment by faboweb** [comment] 2018-10-05 14:50
My mistake. I apologise.
So when there is no problem with stopping and starting, maybe we are actually launching two processes? Maybe we send a reconnect twice and the main process doesn't handle this well?

**Comment by NodeGuy** [comment] 2018-10-05 15:31
Sure, maybe, but it's hard to know.  I say we close this issue until we see the problem again and then jump on it immediately to figure out what's happening.

**Comment by faboweb** [comment] 2018-10-06 18:16
The issue appears frequently and was even reported by a user (https://github.com/cosmos/voyager/issues/1372). Does that log help?

**Comment by NodeGuy** [comment] 2018-10-08 15:11
No, but after looking at it further I see we can protect [startLCD](https://github.com/cosmos/voyager/blob/649722825347ae8f76c40ffb8d22f092e20e265f/app/src/main/index.js#L258-L299) with a mutex.  Let's try that.

**Closed** 2018-10-16 21:30 UTC
Labels: bug
