### ISSUE TITLE
notification spam

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#870] opened 2018-06-22 14:02 UTC
often, when there is an error we send a bunch of notifications. i think we should either limit it to one at a time or debounce them. not sure the best way to handle this - maybe a notifications page?

"yeah, i get it"

<img width="498" alt="screen shot 2018-06-22 at 10 00 29 am" src="https://user-images.githubusercontent.com/6021933/41780604-32bf4718-7603-11e8-851d-96c51badb1bd.png">

**Comment by nylira** [comment] 2018-06-22 14:07
This is duplicate of #844 -- will continue discussion there

**Closed by nylira** 2018-06-22 14:07 UTC
