### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1448] opened 2018-10-10 09:30 UTC
https://sentry.io/tendermint/cosmos-voyager/issues/721488207/

```
TypeError: Cannot read property 'find' of undefined
  at None (/private/var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/AppTranslocation/FD9AD0B2-9F0C-43F2-821D-5C2274D82C01/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:131776:56)
  at Array.filter (<anonymous>)
  at Object._callee9$ (/private/var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/AppTranslocation/FD9AD0B2-9F0C-43F2-821D-5C2274D82C01/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:131775:59)
  at tryCatch (/private/var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/AppTranslocation/FD9AD0B2-9F0C-43F2-821D-5C2274D82C01/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:82089:40)
  at Generator.invoke [as _invoke] (/private/var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/AppTranslocation/FD9AD0B2-9F0C-43F2-821D-5C2274D82C01/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:82323:22)
...
(27 additional frame(s) were not displayed)
```

**Comment by fedekunze** [comment] 2018-11-07 16:54
On Oct 10th the user delegated atoms and then went to the wallet page, so it might be related with loading staking transactions. 

I can't find any `.find` either on the wallet pages nor on the transaction module so I'm closing the issue as I can't reproduce the bug

**Closed by fedekunze** 2018-11-07 16:54 UTC
Labels: bug 🐞
