### ISSUE TITLE
Improve notification on no node found situation

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1532] opened 2018-11-07 14:31 UTC
In the case of no connection:
do not dispay the full screen modal - but instead rely on the network-connectivity-bar to change states from green to orange and display 1 non-invasive popup that says "we're going to keep trying to connect to a good node for you. in the mean time, your experience may be degraded and we would recommend against making any transactions".

also: prevent notification popup spam like here:
<img width="1192" alt="screen shot 2018-11-01 at 12 19 46 pm" src="https://user-images.githubusercontent.com/6021933/47864635-7e7f2d00-ddd0-11e8-9cf3-29e963b08808.png">

**Comment by NodeGuy** [comment] 2018-11-07 16:36
Duplicate of https://github.com/cosmos/voyager/issues/1511.

**Comment by faboweb** [comment] 2018-11-07 21:00
This is split out from that issue.

**Comment by NodeGuy** [comment] 2018-11-08 18:36
Oh, sorry.

**Comment by faboweb** [comment] 2018-11-20 17:04
Change naming to "Node is not reachable"
Add option to retry or use mocked version

**Comment by faboweb** [comment] 2018-11-27 15:59
Working on this in #1533

**Comment by faboweb** [comment] 2018-12-11 11:32
Done in #1533

**Closed** 2018-12-11 11:32 UTC
Labels: design-work-needed, high priority
