### ISSUE TITLE
"Couldn't read keys Network Error"

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#706] opened 2018-05-16 18:12 UTC
> Thank you for filing an issue!

### Version

0.4.3

### Description

When I launch the release version of the app for gaia-5000 on macOS it reports the error in the attached screenshot.

<img width="1136" alt="screen shot 2018-05-16 at 2 04 13 pm" src="https://user-images.githubusercontent.com/2148537/40135104-6c62e2c6-5912-11e8-9a56-ae994ad8f5fb.png">

I'm able to connect to `http://localhost:9071/keys` manually so it looks like a spurious/timing error.

### Log

[main.log](https://github.com/cosmos/voyager/files/2010325/main.log)

**Comment by mappum** [comment] 2018-05-29 06:20
I'm unable to reproduce this on develop, could this have been fixed in recent changes?

**Comment by mappum** [comment] 2018-06-01 20:50
Yes, I was trying the release. If it's a timing issue, we should try to analy,e logs for everything that happens at startup (might need to add more logging).

**Comment by faboweb** [comment] 2018-06-02 15:13
Waiting for the LCD to start is still a timeout I think. Maybe we can
ourselfs add an output to the LCD startup process when it has started to
get rid of the timeout?


Matt Bell <notifications@github.com> schrieb am Fr., 1. Juni 2018, 22:50:

**Closed** 2018-06-26 07:59 UTC
Labels: bug
