### ISSUE TITLE
"About Cosmos Voyager" menu does nothing on Windows.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#793] opened 2018-06-06 00:40 UTC
UI Version: 604b15ffc6acf45f3b5bcdbe12cfbec56965f7b0

Description:

I select the menu `Cosmos Voyager/About Cosmos Voyager` and nothing happens.  I expect to see an about box.

**Comment by faboweb** [comment] 2018-06-06 01:58
Dupe of #767

**Closed by faboweb** 2018-06-06 01:58 UTC
Labels: bug
