### ISSUE TITLE
fresh 0.6.0 bugs 🐛🐜🐞

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#720] opened 2018-05-18 17:17 UTC
> Thank you for filing an issue!

### Version

v0.6.0

### Description

noticed a few issues right off the bat

- first time i opened the app, created a new account, was still on gaia-5000, had to quit and restart app to get to gaia-5001
- fresh install, create new account, sign out - account will not be there to sign back in until you restart the app
- clicking on the mocked option in settings worked nicely, but unclicking does not set network back to gaia-5001
- sign out while in mocked mode goes to sign in screen - but account doesn't exist on mocked server (confusing ux) - also shows `network error: keys` on sign out
- if available balance is 0 - loading screen persists unless you hit refresh
- link to staking is still visible - and route still works (supposed to be hidden)
- onboarding tutorial checkbox takes you back to onboarding modals when trying to mark it as completed

**Comment by NodeGuy** [comment] 2018-05-21 19:30
> * onboarding tutorial checkbox takes you back to onboarding modals when trying to mark it as completed

I couldn't reproduce this.

**Comment by nylira** [comment] 2018-05-22 05:52
> * onboarding tutorial checkbox takes you back to onboarding modals when trying to mark it as completed

The bug where the onboarding tutorial shows up after every app restart has been fixed in #717 This resolves the root of this problem.

The settings checkbox for onboarding isn't for marking it completed. It's for toggling it, like the other checkboxes. Checkboxes are not the correct UX, which is mentioned in #669

**Comment by faboweb** [comment] 2018-05-22 12:00
Staking doesn't show:
![image](https://user-images.githubusercontent.com/5869273/40361066-5d090d2c-5dc8-11e8-9799-358b274211e3.png)

**Comment by faboweb** [comment] 2018-05-22 12:28
Thank you guys for finding and following up on all those bugs! Great teamwork :)

**Comment by faboweb** [comment] 2018-05-24 08:48
Do any of these bugs remain?

**Comment by jolesbi** [comment] 2018-05-25 18:46
i tested these bugs out and all look cleared up except for the one i didn't describe very well. i'll fix it now.

**Closed** 2018-05-27 11:13 UTC
Labels: bug
