### ISSUE TITLE
Optimistic UI implementation

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#1284] opened 2018-09-04 16:09 UTC
- [ ] Add in new layouts from https://github.com/cosmos/voyager/issues/1092

**Comment by NodeGuy** [comment] 2018-09-04 19:39
Please add the `discuss` label to all new issues.

**Comment by NodeGuy** [comment] 2018-10-01 18:55
Can this be moved to `staking2`?

**Comment by jbibla** [comment] 2018-10-01 19:03
though i want to say yes, for the sake of "progress", i really think this is less to do with staking and more to do with the whole voyager ux. the principles discussed in #1092 apply to all the features and will elevate the ux for all areas of the app.

so no. i don't think so. but we can make it high priority and remove the staking label 😄

**Comment by jbibla** [comment] 2018-12-12 18:08
this problem? https://github.com/cosmos/voyager/issues/1092#issuecomment-418142498

**Comment by faboweb** [comment] 2018-12-13 10:03
Yes. I was talking about a technical proposal of how to have a proper process in code (not on the design level).

**Comment by sabau** [comment] 2018-12-18 09:57
Love the idea, I tackled a similar problem years ago I will write down the solution we found and we can discuss it how to adapt/change/discard that :)
- The GUID part I really think is not relevant for this project, as we have a fixed structure and the user cannot modify how the UI looks like by adding or removing tabs, components etc.., We can probably just reference portions of our state

## Real state
- User see everything in his natural color and opacity

## Unconfirmed state / transactions
- Blocks are what I expect on certain part of my state to happen if my transaction succeed
- There are two possible blocks: newItems and deltas
- Every part of the state can be logically composed by blocks and Referenced by (GUID or similar) generic IDS not referring to any particular area, just generic IDS, the block describe where he will will have an impact
- at rendering time we show the Real state, for every component we know a GUID is present, so we simply check in our dictionary of the unconfirmed states / transactions if this component has a WIP, we choose to show the unconfirmed block (or the delta when needed)
  - example: I made a transaction, I will add 2 unconfirmend blocks:
    - The new transaction that still does not exists on my transactions list (corner case) we should show them on top?
    - The new Balance as Delta []
    - I do another transaction: 
- Everything that has a WIP must have an icon or a diffent grey-ish color to clearly differentiate from a final state or transaction (if I have a list of 3 items and only one is work in progress, it must be clear and easily identifiable the difference between the two)
- once the transaction is confirmed, if the user is actively watching a component that change state, we need a smooth transition, if he's not watching we can choose do just change or show notifications depending on the criticality of the block we want to change

**Comment by sabau** [comment] 2018-12-18 17:22
we can do in simpler way:
 - not everything needs to have this unfconfirmed state
 - isolated states

Alternative approach:
- Just update the state as if succeeded
- then query for the next block

**Comment by jbibla** [comment] 2019-01-17 15:30
closed in favour of #1849

**Closed by jbibla** 2019-01-17 15:30 UTC
Labels: epic, low priority, split 🍌
