### ISSUE TITLE
The gaiacli rest-server (LCD) experienced an error: panic: resource temporarily unavailable goroutine 1 [running]:

### ISSUE THREAD

**Issue by runlin512** [cosmos/voyager#1425] opened 2018-10-07 12:30 UTC
UI Version: 0.X.X

Description:

The gaiacli rest-server (LCD) experienced an error: panic: resource temporarily unavailable goroutine 1 [running]:

**Comment by faboweb** [comment] 2018-10-07 14:05
Dupe of #1376

**Closed by faboweb** 2018-10-07 14:05 UTC
