### ISSUE TITLE
Create deterministic installers.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#969] opened 2018-07-13 21:35 UTC
Fabo inquired about using electron-builder and [found that it's non-deterministic](https://github.com/electron-userland/electron-builder/issues/2454).

We had [a conversation](https://github.com/cosmos/voyager/pull/329) earlier about using electron-builder.

**Comment by NodeGuy** [comment] 2018-07-17 22:46
Tools that create installers for Electron applications:

* [electron-winstaller](https://github.com/electron/windows-installer)
* [Electron Forge](https://electronforge.io/)
* [Electron Installer Grunt Plugin](https://github.com/electron-archive/grunt-electron-installer)

**Comment by fedekunze** [comment] 2018-08-30 11:56
@NodeGuy do you think we should also proceed with #908 either with [electron-installer-zip](https://github.com/electron-userland/electron-installer-zip) or [electron-installer-dmg](https://github.com/electron-userland/electron-installer-dmg) ?

**Comment by fedekunze** [comment] 2018-08-30 12:05
**Note**: Bitcoin Core uses the [Gitian builder](https://github.com/devrandom/gitian-builder) for deterministic builds. Here is the link to the [setup instructions](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md)

**Comment by faboweb** [comment] 2018-08-30 12:32
But this is just the environment right? The build process also needs to be deterministic.

**Comment by fedekunze** [comment] 2018-08-30 12:42
In the case of Linux, I'd definitely go for Flatpak. It has long list of advantages (see https://github.com/signalapp/Signal-Desktop/issues/1639#issuecomment-342422537) as well as an App store [Flathub](https://flathub.org/home).  There are other concerns related to Flathub's security stated in https://github.com/signalapp/Signal-Desktop/issues/1639#issuecomment-347410590 that we'd have to investigate

**Comment by NodeGuy** [comment] 2018-08-30 19:30
> @NodeGuy do you think we should also proceed with #908 either with electron-installer-zip or electron-installer-dmg ?

electron-installer-zip doesn't create an installer so it doesn't seem very interesting.

electron-installer-dmg isn't deterministic (see [my issue](https://github.com/electron-userland/electron-installer-dmg/issues/33)).

**Comment by NodeGuy** [comment] 2018-08-30 19:32
The owner of node-appdmg [responded enthusiastically](https://github.com/LinusU/node-appdmg/issues/166#issuecomment-417310148) about working together to make it deterministic but we're now outside the time box of 1 day.  @faboweb How should we reply?

**Comment by faboweb** [comment] 2018-08-31 09:06
This sounds like a longer endeavour. Let's respect the timebox and come back to it later. There are new proposals about handling this issue.

**Comment by fedekunze** [comment] 2018-08-31 11:11
Blocked: waiting for @jessysaurusrex 's input on security

**Comment by jessysaurusrex** [comment] 2018-09-01 02:04
Where did the requirement for the installer to be deterministic come from? Given some of the constraints that are mentioned above, it seems like we should wait for electron-builder to mature a bit more since there are other ways to address the risks at hand.

In this case, especially since we are talking about code that includes Electron (which is a huge project that we absolutely do not want to fork/write a new library for right now), it would be best for us to move forward by signing our binaries so that third parties are able to verify that they're using what we've marked for distribution.

**Comment by faboweb** [comment] 2018-09-03 09:41
@jessysaurusrex if having non deterministic binaries is enough from a security perspective, let's only go with signing. how would you setup the process of signing the binaries?

**Comment by jessysaurusrex** [comment] 2018-09-04 21:13
On our end, we'll need to make sure that we have some infrastructure in place in the form of secure secure servers (Windows, Mac, Linux machines) that are offline or that we can run from an automated and reproducible state... and we'll need to store the signing cert offline to reduce risk (possibly on a Ledger).  That's a bit of a operations work plus some planning in the certificate/key management realm, in addition to the actual process for signing our binary.   

Is this something you'd just like a high level plan for, or should it be an end-to-end process? I can begin following up on the server/cert management piece tomorrow, @faboweb.

**Comment by faboweb** [comment] 2018-09-05 11:37
@jessysaurusrex thx for offering help. I will clarify some things today and ping you afterwards.

**Comment by faboweb** [comment] 2018-09-24 12:51
Closing this as we will no longer aim to deliver an installable application.

**Closed by faboweb** 2018-09-24 12:51 UTC
Labels: blocked, technical
